config/routes.rb
Rails.application.routes.draw do
  get 'pages/admin', :as=> 'admin_page'

  resources :posts
  devise_for :users
  resources :images, :comments
  root to:"home#index"
  resources :users

  get "users/:id" => "users#show"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end

  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user

  default_scope { order("created_at DESC") }
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :comments
  mount_uploader :picture, PictureUploader
end

app/models/page.rb
class Page < ActiveRecord::Base
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  default_scope { order("created_at DESC") }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :authentication_keys => [:username]

  has_many :comments
  has_many :posts

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :name, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :password, :remember_me)}
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :name, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_name = current_user.username

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :image_id)
    end
end

app/controllers/home_controller.rb
class HomeController<ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.uploaded_by = current_user.name

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
      @comments = @image.comments.all
      @comment = @image.comments.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def admin
    @users = User.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @users = User.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.posted_by = current_user.name

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:posted_by, :post_text)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Portal"
    if page_title.present?
      "#{page_title} - Portal"
    else
      "Portal"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <hr>
  <div class="field">
    <%= f.label "Leave a comment" %><br>
    <%= f.text_area :body %>
  </div>
  <%= f.hidden_field :image_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <h1>All Comments</h1>

  <table>
    <thead>
      <tr>
        <th>User name</th>
        <th>Body</th>
        <th>Image</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.user_name %></td>
          <td><%= comment.body %></td>
          <td><%= comment.image_id %></td>
          <td><%= link_to 'Show', comment %></td>
          <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Comment', new_comment_path %>
</div>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Image:</strong>
  <%= @comment.image_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', images_path %>

app/views/home/index.html.erb
<% content_for :title, "Home" %>

<div class="row">

  <div class="home-header">
    <div class="home-header-top">
      <div class="home-header-image">
        <%= image_tag("family-img-1.jpg") %>
      </div>
    </div>
    <div class="home-header-bottom hide-for-medium-down">
      <div>
        <%= image_tag("family-img-2.jpg", size: "190x66") %>
      </div>
      <div>
        <%= image_tag("family-img-3.jpg", size: "190x66") %>
      </div>
      <div>
        <%= image_tag("family-img-4.jpg", size: "190x66") %>
      </div>
    </div>
  </div>

  <div class="medium-7 columns">
    <div class="posts-home">
      <h3>Most recent posts</h3>
      <% @posts.limit(10).each do |post| %>
        <div>
          <p><%= post.post_text %></p>
          <p>- <span class="posted-by-name"><%= post.posted_by %></span> <span class="posted-at"><%= post.created_at.strftime("%d %b %y") %></span></p>
          <!-- <td><%= link_to 'Show', post %></td> -->
          <hr />
        </div>
      <% end %>
    </div>
  </div>
  <div class="medium-5 columns">
    <div id='calendar'></div>
    links and stuff here too?
  </div>
</div>

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<% content_for :title, "Image Gallery" %>
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="small-11 columns">

    <h1>Image Gallery</h1>
    <%= link_to 'Upload a new image', new_image_path, class: "button" %>

    <div>

        <% @images.each do |image| %>
          <div class="medium-2 large-2 small-3 columns">
            <%= link_to(image) do %>
              <%= image_tag image.picture_url(:thumb) if image.picture? %>
            <% end %>
          </div>
          <div class="medium-8 large-7 small-7 columns">
            <%= link_to(image) do %>
            <h3><%= image.name %></h3>
            <% end %>
            <p><%= image.description %></p>
          </div>
          <div class="small-2 columns">
            <%= image.uploaded_by %><br/>
            <% if current_user.name == image.uploaded_by || current_user.username == "elizabethh" %>
              <%= link_to 'Edit', edit_image_path(image) %> | <%= link_to 'Delete', image, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
          <hr />
        <% end %>

    </div>

    <br>

  </div>
</div>

app/views/images/new.html.erb
<div class="row new-image-page">
  <h1>New Image</h1>
  <p>All images are saved down to 800px by 800px if they are bigger than that size. This is just so the image doesn't load so big no one can see it. If you need to upload a large image for printing (like a family picture you want others to print at a high quality), please contact Beth.</p>

  <%= render 'form' %>

  <%= link_to 'Back', images_path %>
</div>

app/views/images/show.html.erb
<% content_for :title, "Image" %>

<div class="row">
  <div class="small-11 small-centered columns">
    <h3><%= @image.name %></h3>
    <p><%= @image.description %></p>

    <p>
      <%= image_tag(@image.picture_url) if @image.picture.present? %>
    </p>

    <% if current_user.name == @image.uploaded_by || current_user.username == "elizabethh" %>
      <%= link_to 'Edit this image', edit_image_path(@image), class: "button" %>
    <% end %>

    <h3>Comments</h3>
    <% @comments.each do |comment| %>
      <div>
        <strong><%= comment.user_name %></strong>
        <br />
        <p><%= comment.body %></p>
        <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </div>
    <% end %>
    <%= render 'comments/form' %>

    <%= link_to 'Back', images_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title yield(:title) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "fullcalendar/gcal.js" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,300,200,700' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div class="wrapper">

      <div class="header">
        <!-- this is the header, to be moved when we cover inserting partials -->
        <nav class="top-nav">
          <section id="gradient-top-bar"></section>
          <div class="top-nav-left">
            <% if user_signed_in? %>
              Welcome <strong><%= current_user.name %></strong>.
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% end %>
          </div>
          <div class="top-nav-center">
            <%= link_to(root_path) do %>
              <h3>
                Huntsman<br/>
                <span class="title">Family Website</span>
              </h3>
            <% end %>
          </div>
          <div class="top-nav-right">
            <% if user_signed_in? %>
            <%= link_to "View all posts", posts_path %> |
            <%= link_to "Image library", images_path %> |
            <%= link_to 'Change password', edit_user_registration_path, :class => 'navbar-link' %>
            <% end %>
          </div>
        </nav>
      </div>

      <div class="container">

        <!-- <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %> -->

        <%= yield %>

      </div>

      <% if user_signed_in? %>
        <div class="footer">
          <div class="row">
            <div class="medium-6 small-12 columns">
              <%= link_to "View all posts", posts_path %>
            </div>
            <div class="medium-6 small-12 columns">
              <%= link_to "Image library", images_path %>
            </div>
            <% if current_user.username == "elizabethh" %>
              <hr />
              <div class="12-small columns">
                <%= link_to "sign up new user", admin_page_path %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>

    </div>
  </body>
</html>

app/views/pages/admin.html.erb
<% content_for :title, "Admin" %>

<% if current_user.username == "elizabethh" %>

<div class="row">
  <div class="small-10 small-centered columns">

    <h1>Admin page</h1>
    <h3>Create a new user</h3>

    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>

      <div class="field">
        <%= f.label :username %><br />
        <%= f.text_field :username, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <% if @validatable %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
      </div>

      <div class="actions">
        <%= f.submit "Sign up" %>
      </div>

    <% end %>

    <hr/>

    <h3>User list</h3>

    <table>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.username %></td>
            <td><%= user.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "add a new post:" %><br>
    <%= f.text_area :post_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% content_for :title, "Edit Post" %>
<div class="row">
  <h1>Editing Post</h1>

  <%= render 'form' %>
  <%= link_to 'Back to all posts', posts_path %>
</div>

app/views/posts/index.html.erb
<% content_for :title, "Posts" %>
<p id="notice"><%= notice %></p>
  <div class="row">
  <h1>All Posts</h1>
  <%= link_to 'Make a new post', new_post_path, class: "button" %>
  <div class="posts-home">

      <% @posts.each do |post| %>
        <div>
          <p><%= post.post_text %></p>
          <p>- <span class="posted-by-name"><%= post.posted_by %></span> <span class="posted-at"><%= post.created_at.strftime("%d %b %y") %></span></p>
          <!-- <td><%= link_to 'Show', post %></td> -->
          <% if current_user.name == post.posted_by || current_user.username == "elizabethh" %>
            <%= link_to "edit post", edit_post_path(post) %> | <%= link_to 'delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          <hr />
        </div>
      <% end %>

  </div>

</div>

app/views/posts/new.html.erb
<% content_for :title, "New Post" %>
<div class="row">
  <h1>New post</h1>

  <%= render 'form' %>

  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div>
    <p><%= @post.post_text %></p>
    <p>- <span class="posted-by-name"><%= @post.posted_by %></span> <span class="posted-at"><%= @post.created_at.strftime("%d %b %y") %></span></p>
    <% if current_user.name == @post.posted_by || current_user.username == "elizabethh" %>
      <%= link_to "edit post", edit_post_path(@post) %>
    <% end %> |
  <%= link_to 'Go to all posts', posts_path %>
</div>